[custom.all.uv]
type = "local"
path = "."
ipkg = "uv.ipkg"
test = "test/test.ipkg"

[custom.all.uv-data]
type = "local"
path = "data"
ipkg = "uv-data.ipkg"

[custom.all.uv-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.uv-docs]
type = "local"
path = "docs"
ipkg = "uv-docs.ipkg"
